package audio;

// Very simple class just so exceptions generated by AudioPlayer
// can be easily recognized.

public class AudioPlayerException extends Exception{

    public AudioPlayerException(String message){
        super(message);
    }
}