package audio;

import java.util.*;

/********************************************************/
/**
 * The AudioPlayerListener interface enables notification
 * of events generated by an AudioPlayer.
 */
public interface AudioPlayerListener extends EventListener{
    /**
     * This function is called whenever an AudioPlayer state
     * change occurs.
     */
    public void audioStateChanged(AudioPlayer.State newState);  
}